// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6_jab468.Models;

namespace Mission6_jab468.Migrations
{
    [DbContext(typeof(blahContext))]
    [Migration("20230214044712_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission6_jab468.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action",
                            DirectorFirstName = "Johnny",
                            DirectorLastName = "Appleseed",
                            Edited = false,
                            Rating = "R",
                            Title = "Fast and Furious",
                            Year = "1911"
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action",
                            DirectorFirstName = "Johnny",
                            DirectorLastName = "Appleseed",
                            Edited = false,
                            Rating = "R",
                            Title = "Fast and Furious 2",
                            Year = "1912"
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action",
                            DirectorFirstName = "Johnny",
                            DirectorLastName = "Appleseed",
                            Edited = false,
                            Rating = "R",
                            Title = "Fast and Furious 3",
                            Year = "1913"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
